require "cash_flow_analysis/version"
require "cash_flow_analysis/calculation_error"
require "cash_flow_analysis/calculator/cagr"
require "cash_flow_analysis/calculator/payment"
require "cash_flow_analysis/calculator/xirr"
require "cash_flow_analysis/calculator/xnpv"
require "cash_flow_analysis/util/objective_function"
